from math import sqrt, pi

datos_entrada_dict = {
'Sistema': 'trifasico',
'lineas': 3,
'Voltaje': 230,
'Carga': 480*sqrt(3)*230*0.9,
'fp': 0.9,
'factor_utilizacion_carga': 1,
'factor_simultaneidad_carga': 1,
'Interruptor_forzado': 0,
'factor_Inominal_Interruptor': 2.5,
'tipo_circuito': 'derivado',
'caida_tension': 3,
'Longitud': 50,
'Tambiente': 40,
'aislante_conductor': 'THHN',
'Taislante': 90,
'Tterminales': 75,
'material_conductor': 'cobre',
'numero_conductores_por_fase': 2,
'numero_conductores_neutro': 0,
'factor_Inominal_fase_aplicado_neutro': 0,
'neutro_activo_factor_agrupamiento': False,
'tierra_fisica_forrada': False,
'adicionar_tierra_fisica_aislada': False, 
'canalizacion': 'conduit',
'tipo_conduit': 'HDPE',
'conduit_pulg_forzado': '3',
'material_canalizacion': 'pvc',
'misma_canalizacion': False,
'conductores_activos_adicionales_misma_canalizacion': {},
'conductores_no_activos_adicionales_misma_canalizacion': {},
}

#datos_por_defecto_Calculos_dict = {'factor_ampacidad_cable_neutro': 1} #Sobreescritura de datos por defecto en los calculos

datos_entrada_descripcion_dict = {
'Sistema': "'Sistema ('monofasico',  'trifasico')'",
'lineas': '(1, 2, 3) Para sistemas trifásicos puedes usar 1, 2 o 3 lineas, para sistemas monofásicos pueden ser 1 o 2 lineas',
'Voltaje': 'Voltaje nominal = Voltaje de linea (V)',
'Carga': 'Carga (W)',
'fp': 'factor de potencia (>0 a 1)',
'factor_utilizacion_carga': 'Fracción utilizada de la Carga/Carga (>0 a 1). Ejemplo: Un motor se utiliza al 80%, por lo tanto, factor_utilizacion_carga = 0.8',
'factor_simultaneidad_carga': 'Cargas individuales utilizadas al mismo tiempo/Carga (>0 a 1). NOTA: Aplica cuando Carga esta formada de cargas individuales',
'Interruptor_forzado': 'Sino quieres fijar un interruptor por defecto: Interruptor_forzado = 0. Se fija el valor de un interruptor y se verifica si dicho interruptor cumple con los criterios en calculo_Interruptor, sino cumple, se elige un interruptor de forma normal de forma automática',
'factor_Inominal_Interruptor': 'El valor del Interruptor se calculará en base a Interruptor >= Inominal*factor_Inominal_Interruptor, siempre que factor_Inominal_Interruptor > 1/factor_utilizacion_interruptor',
'tipo_circuito': "('sin especificar', 'derivado', 'alimentador', 'acometida')'",
'caida_tension': 'Caída de tensión (%)',
'Longitud': 'Longitud (m) Nota: 0.60 m y menos, no se aplica factor de agrupamiento',
'Tambiente': 'Temperatura ambiente (°C)',
'aislante_conductor': "('THW, THHW, THW-2', 'THHN, THWN, THWN-2', 'XHHW, XHHW-2, XHH', 'RHH, RHW, RHW-2', 'RHH*, RHW*, RHW-2*') Aislante del conductor. NOTA: Todo en mayúsculas",
'Taislante': '(60, 75, 90) Temperatura del aislante del conductor(°C)',
'Tterminales': '(60, 75, 90) Temperatura menor de las terminales para cable en el circuito (°C)',
'material_conductor': "'Material del conductor ('cobre', 'aluminio')'",
'numero_conductores_por_fase': 'Número de conductores por fase',
'numero_conductores_neutro': 'Número de conductores de neutro. Para circuitos de 2 y 3 lineas, el uso del neutro es opcional, para 1 linea siempre debe de ser 1. NOTA: Se permite mayor número de conductores de neutro que de fase. En circuitos con cables en paralelo el diametro de la canalización sera el que tenga mayor número de cables. El aislante del conductor de fase y neutro se considera que es el mismo que aislante_conductor',
'factor_Inominal_fase_aplicado_neutro': 'Inominal_neutro = Inominal_fase*factor_Inominal_fase_aplicado_neutro',
'neutro_activo_factor_agrupamiento': '(True, False) ¿El neutro transporta corriente?. Se usa para calcular el factor de agrupamiento en la canalización',
'tierra_fisica_forrada': '(True, False) ¿El conductor de tierra fisica esta forrado por algun aislante?. El aislante del conductor se considera que es el mismo que aislante_conductor',
'adicionar_tierra_fisica_aislada': '(True, False) ¿Se adiciona un conductor de tierra fisica aislada?. El aislante del conductor se considera que es el mismo que usa el conductor de fase', 
'canalizacion': 'conduit',
'tipo_conduit': "'EMT', 'IMC', 'EMT', 'ENT', 'FMC', 'IMC', 'LFNC-A*', 'LFNC-B*', 'LFNC-C*', 'LFMC', 'RMC', 'PVC, cédula 80', 'PVC, cédula 40', 'HDPE', 'PVC, tipo A', 'PVC, tipo EB'",
'conduit_pulg_forzado': 'Sino quieres fijar un conduit por defecto designado en pulgadas: conduit_pulg_forzado = 0. Se fija el valor de un conduit en pulgadas y se verifica si dicho valor cumple con el porcentaje de llenado correspondiente,  sino cumple, se elige un tamaño de conduit de forma normal de forma automática',
'material_canalizacion': "'Material de la canalizacion NOTA: Usada solo para calcular caída de tensión ('acero', 'pvc', 'aluminio')'",
'misma_canalizacion': '(True, False) Colocar el total de los conductores de fase, neutro, tierra fisica normal, tierra fisica aislada en la misma canalización?: (True NOTA: Nada recomendable cuando es mas de un conductor por fase, False NOTA: Si es recomendable)',
'conductores_activos_adicionales_misma_canalizacion': "Número de conductores portadores de corriente adicionales a los calculados para el circuito. Estos conductores estaran presentes siempre en la canalización calculada, sea misma_canalizacion = True o False. NOTA: Estos conductores siempre se consideran que tienen aislante y que es el mismo que aislante_conductor. Ejemplo: 1 conductor calibre 14, 2 conductores calibre 1/0 => {'14': 1, '1/0': 2}. Sino hay => {}",
'conductores_no_activos_adicionales_misma_canalizacion': "Número de conductores no portadores de corriente adicionales a los calculados para el circuito. Estos conductores estaran presentes siempre en la canalización calculada, sea misma_canalizacion = True o False. NOTA: Estos conductores siempre se consideran que no tienen aislante. Ejemplo: 0 conductores 250 kcmil, 3 conductores calibre 4/0 => {'250': 0, '4/0': 3}. Sino hay => {}",
}

datos_salida_descripcion_dict = {
'Inominal_fase': 'Cálculo de la corriente nominal en las fases del circuito eléctrico, suponiendo un circuito balanceado',
'Inominal_neutro': 'Después de hacer los cálculos correspondientes para Inominal_neutro, se procede a Inominal_neutro = Inominal_fase*factor_Inominal_fase_aplicado_neutro. Cálculo de la corriente nominal en el neutro del circuito eléctrico, suponiendo un circuito balanceado',
'Icorregida_factor_ampacidad_cable_fase': 'Icorregida_factor_ampacidad_cable_fase = Inominal_fase*factor_ampacidad_cable_fase, factor_ampacidad_cable_fase = 1.25 por defecto, más información de factor_ampacidad_cable_fase en Calculos.__init__.datos_por_defecto_Calculos_descripcion_dict',
'Icorregida_factor_ampacidad_cable_neutro': 'Icorregida_factor_ampacidad_cable_neutro = Inominal_neutro*factor_ampacidad_cable_neutro, factor_ampacidad_cable_neutro = 1.25 por defecto, más información de factor_ampacidad_cable_neutro en Calculos.__init__.datos_por_defecto_Calculos_descripcion_dict',
'Carga_corregida_factor_utilizacion_carga': 'Carga_corregida_factor_utilizacion_carga = Carga*factor_utilizacion_carga',
'Carga_corregida_factor_simultaneidad_carga': 'Carga_corregida_factor_simultaneidad_carga = Carga*factor_simultaneidad_carga',
'numero_conductores_por_fase': 'Número de conductores por fase',
'numero_conductores_neutro': 'Número de conductores de neutro. Para circuitos de 2 y 3 lineas, el uso del neutro es opcional, para 1 linea siempre debe de ser 1. NOTA: Se permite mayor número de conductores de neutro que de fase. En circuitos con cables en paralelo el diametro de la canalización sera el que tenga mayor número de cables. El aislante del conductor de fase y neutro se considera que es el mismo que aislante_conductor',
'factor_Inominal_fase_aplicado_neutro': 'Inominal_neutro = Inominal_fase*factor_Inominal_fase_aplicado_neutro',
'neutro_activo_factor_agrupamiento': '(True, False) ¿El neutro transporta corriente?. Se usa para calcular el factor de agrupamiento en la canalización',
'conductores_activos_canalizacion': 'Conductores activos en la canalización en la que se encuetra el circuito, el conductor neutro se considera activo dependiendo del tipo de circuito, en circuitos donde la Inominal = 0, se considera no activo a menos de que se exprese explicitamente en neutro_activo_factor_agrupamiento = True. Para circuitos con conductores en paralelo y misma_canalizacion = False, numero_conductores_por_fase es igual al número de canalizaciones para los conductores en paralelo, cada canalización contendra un juego de conductores de fase + conductores neutros repartidos por igual y hasta colocar todos los conductores neutros en las canalizaciones, por ejemplo, si hay 3 canalizaciones y 2 conductores neutros habrá una canalización sin neutro, si hay 3 canalizaciones y 4 conductores neutro, habrá 1 canalización con 2 conductores neutros',
'Interruptor': 'Interruptor seleccionado en base a todos los criterios introducidos en los datos de entrada',
'porcentaje_utilizacion_Interruptor': 'porcentaje_utilizacion_Interruptor = Inominal*100/Interruptor',
'factor_temperatura': 'factor de temperatura en base a la temperatura_ambiente y la temperatura base de la tabla de ampacidad correspondiente que se uso en el cálculo',
'factor_agrupamiento': 'factor de agrupamiento en base a conductores_activos_canalizacion',
'calibre_ampacidad_fase': 'calibre elegido por ampacidad para cada conductor de fase en base a los datos de entrada',
'Area_ampacidad_fase': 'Área en mm^2 del conductor de fase elegido por ampacidad', 
'Ampacidad_fase': 'Ampacidad del conductor de fase en la tabla de ampacidad correspondiente para este cálculo', 
'Ampacidad_corregida_fase': 'Ampacidad_corregida_fase = Ampacidad_fase*factor_agrupamiento*factor_temperatura',
'calibre_caida_fase': 'calibre elegido por caída de tensión para cada conductor de fase en base a los datos de entrada',
'Area_caida_fase': 'Área en mm^2 del conductor de fase elegido por caída de tensión',
'caida_tension_calculada': 'caída de tensión calculada en porcentaje',
'calibre_cable_fase': 'selección final del calibre para cada conductor de fase en base a los datos de entrada',
'Area_cable_fase': 'Área en mm^2 de calibre_cable_fase',
'calibre_tierra_fisica': 'selección del calibre para tierra física para el circuito de acuerdo a la tabla correspondiente', 
'Area_tierra_fisica': 'Área en mm^2 de calibre_tierra_fisica',
'factor_correccion_cable_tierra_fisica': 'factor_correccion_cable_tierra_fisica = Area_caida_fase/Area_ampacidad_fase, este factor se aplica a Area_tierra_fisica para seleccionar Area_tierra_fisica_corregida_caida_ideal',
'Area_tierra_fisica_corregida_caida_ideal': 'Área calculada en mm^2 del conductor de tierra fisica en base a factor_correccion_cable_tierra_fisica',
'calibre_tierra_fisica_corregida_caida': 'calibre de la tierra física seleccionada en base al valor inmediatamente superior del Area_tierra_fisica_corregida_caida_ideal',
'Area_tierra_fisica_corregida_caida': 'Área en mm^2 de calibre_tierra_fisica_corregida_caida',
'calibre_tierra_fisica_final': 'selección del calibre mayor en base a todos los cálculos previos del conductor de tierra física',
'Area_tierra_fisica_final': 'Área en mm^2 de calibre_tierra_fisica_final',
'calibre_tierra_fisica_aislada': 'este valor es igual a calibre_tierra_fisica_final',
'Area_tierra_fisica_aislada': 'Área en mm^2 de calibre_tierra_fisica_aislada',
'calibre_ampacidad_neutro': 'calibre elegido por ampacidad para cada conductor neutro en base a los datos de entrada', 
'Area_ampacidad_neutro': 'Área en mm^2 del conductor neutro elegido por ampacidad', 
'Ampacidad_neutro': 'Ampacidad del conductor neutro en la tabla de ampacidad correspondiente para este cálculo', 
'Ampacidad_corregida_neutro': 'Ampacidad_corregida_neutro = Ampacidad_neutro*factor_agrupamiento*factor_temperatura',
'calibre_cable_neutro': 'selección final del calibre para cada conductor neutro en base a los datos de entrada', 
'Area_cable_neutro': 'Área en mm^2 de calibre_cable_neutro',
'conductores_circuito': "Es un diccionario de diccionarios con los conductores del circuito: {'L1': {calibre de la línea 1: número de conductores totales del circuito solo para la línea 1}, 'L2': {calibre de la línea 2: número de conductores totales del circuito solo para la línea 2}, 'L3': {calibre de la línea 3: número de conductores totales del circuito solo para la línea 3}, 'N': {calibre del neutro: número de conductores neutro totales del circuito}, 'TF': {calibre de la tierra física: número de conductores de tierra física totales del circuito, uno por cada canalización}, 'TA': {calibre de la tierra física aislada: número de conductores de tierra física aislada totales del circuito, siempre es 1 independiente del número de canalizaciones}}. Ejemplo: {'L1': {'3/0': 2}, 'L2': {'3/0': 2}, 'L3': {'3/0': 2}, 'N': {False: 0}, 'TF': {'2': 2}, 'TA': {False: 0}}",
'conductores_canalizacion': "Conductores totales en la canalización, los forrados tendran el aislante_conductor y por consiguiente su área, los desnudos tienen el área solo del condutor. Es un diccionario de diccionarios con los conductores en la canalización, forrados y desnudos. Ambos, forrados y desnudos se componenen de diccionarios con la misma configuración de conductores_activos_adicionales_misma_canalizacion o conductores_no_activos_adicionales_misma_canalizacion. Ejemplo: {'forrados': {False: 0, '3/0': 3}, 'desnudos': {'2': 1}}",
'Area_conductores': "Área total de todos los conductores con aislante y sin aislante en conductores_canalizacion",
'porcentaje_llenado_conduit': "porcentaje_llenado_conduit = Area_conductores/Area_conduit*100",
'medida_conduit_in': 'medida en pulgadas del tubo conduit seleccionado o forzado',
'medida_conduit_mm': 'medida en mm del tubo conduit seleccionado o forzado',
'Area_conduit': 'Área interna del tubo conduit seleccionado o forzado',
}