from math import sqrt, pi

datos_entrada_dict = {
'Sistema': 'trifasico',
'Voltaje': 100,
'Carga': 10000,
'fp': 1.0,
'caida_tension': 3,
'Longitud': 10,
'Tambiente': 40,
'aislante_conductor': 'THHW',
'Taislante': 90,
'Tterminales': 75,
'material_conductor': 'cobre',
'numero_conductores_por_fase': 1,
'conductores_activos_adicionales_misma_canalizacion': {'14': 0},
'misma_canalizacion': False,
'Interruptor_forzado': 0,
'canalizacion': 'conduit',
'material_canalizacion': 'acero',
'tipo_conduit': 'EMT',
'lineas': 3,
'tamano_neutro_porcentaje_contra_fase': 100,
'numero_conductores_neutro': 1,
'neutro_activo': True,
'factor_utilizacion_carga': 1,
'factor_simultaneidad_carga': 1,
}

#datos_por_defecto_Calculos_dict = {} #Sobreescritura de datos por defecto

datos_entrada_descripcion_dict = {
'Sistema': 'Sistema (\'monofasico\',  \'trifasico\')',
'Voltaje': 'Voltaje (V)',
'Carga': 'Carga (W)',
'fp': 'factor de potencia (>0-1)',
'caida_tension': 'Caída de tensión (%)',
'Longitud': 'Longitud (m) Nota: 0.60 m y menos, no se aplica factor de agrupamiento',
'Tambiente': 'Temperatura ambiente (°C)',
'aislante_conductor': 'Aislante del conductor NOTA: todo en mayúsculas',
'Taislante': 'Temperatura del aislante del conductor (°C)',
'Tterminales': 'Temperatura menor de las terminales para cable en el circuito (°C)',
'material_conductor': 'Material del conductor (\'cobre\', \'aluminio\')',
'numero_conductores_por_fase': 'Número de conductores por fase',
'conductores_activos_adicionales_misma_canalizacion': 'Número de conductores activos adicionales a los calculados para el circuito. Estos conductores estaran presentes siempre en la canalización calculada, sea misma_canalizacion = True o False',
'misma_canalizacion': 'Colocar el total de los conductores de fase y neutro en la misma canalización?: (True NOTA: Nada recomendable cuando es mas de un conductor por fase, False NOTA: Si es recomendable)',
'Interruptor_forzado': '0. No se fija un interruptor por defecto, >0. Se fija un interruptor y se verifica si dicho interruptor cumple con los criterios en calculo_Interruptor, sino cumple, se elige un interruptor de forma normal de forma automática',
'canalizacion': 'Canalización (\'conduit\',\'charola\',\'ducto\')',
'material_canalizacion': 'Material de la canalizacion NOTA: Usada solo para calcular caída de tensión (\'acero\', \'pvc\', \'aluminio\')',
'tipo_conduit': 'EMT',
'lineas': '(1, 2, 3) Para sistemas trifásicos obligatoriamente deben de ser 3 líneas, se aplica por defecto, para sistemas monofásicos pueden ser 2 o 1 lineas',
'tamano_neutro_porcentaje_contra_fase': 'Sección transversal total del conductor neutro en comparación con la sección transversal total del conductor de fase. 100% Uso recomendable (%)',
'numero_conductores_neutro': 'Para circuitos de 3 y 2 lineas, el uso del neutro es opcional, para 1 linea siempre es 1 por defecto. NOTA: No se recomienda mayor número de conductores de neutro que de fase',
'factor_utilizacion_carga': 'Fracción utilizada de la Carga/Carga (>0-1)',
'factor_simultaneidad_carga': 'Cargas individuales de la Carga total utilizadas al mismo tiempo/Carga total (>0-1)',
}